# Generated by Django 3.2.13 on 2022-06-30 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_personel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personel',
            old_name='departement',
            new_name='department',
        ),
    ]
