# Generated by Django 3.2.13 on 2022-07-03 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_area_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='coordinator',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.personel'),
        ),
    ]
