# Generated by Django 3.2.13 on 2022-07-03 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_area_coordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='coordinator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.personel'),
        ),
    ]
