# Generated by Django 3.2.13 on 2022-07-04 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220704_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.area'),
        ),
    ]
