# Generated by Django 3.2.13 on 2022-07-04 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_personel_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='NcForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('audit_date', models.CharField(max_length=255)),
                ('standard', models.CharField(max_length=255)),
                ('nc_point', models.CharField(max_length=255)),
                ('nc_source', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.area')),
                ('sub_area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.subarea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
