# Generated by Django 3.2.13 on 2022-07-05 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ncform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncform',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area'),
        ),
        migrations.AlterField(
            model_name='ncform',
            name='sub_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subarea'),
        ),
    ]
