# Generated by Django 3.2.13 on 2022-07-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220705_0031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NcForm',
            new_name='Audit',
        ),
    ]
