# Generated by Django 3.2.13 on 2022-07-05 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_ncform_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='verified_date',
            field=models.CharField(default='2022-05-01', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Correctiveaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause_analysis', models.TextField(blank=True)),
                ('corrective_actions', models.TextField(blank=True)),
                ('due_date', models.CharField(max_length=255)),
                ('pre_actions', models.TextField(blank=True)),
                ('links', models.CharField(max_length=255)),
                ('audit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.audit')),
                ('prepared_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.personel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
