# Generated by Django 3.2.14 on 2022-07-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220705_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='verification_note',
            field=models.TextField(blank=True),
        ),
    ]
