# Generated by Django 3.2.14 on 2022-07-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_standardpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpoint',
            name='description',
            field=models.CharField(default='str', max_length=255),
            preserve_default=False,
        ),
    ]
