# Generated by Django 3.2.14 on 2022-07-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_standardpoint_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpoint',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
