# Generated by Django 3.2.14 on 2022-07-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_standardpoint_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standardpoint',
            old_name='standard',
            new_name='standard_id',
        ),
    ]
