# Generated by Django 3.2.14 on 2022-07-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_audit_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='cat',
            field=models.CharField(choices=[('MJ', 'Major'), ('MI', 'Minor'), ('OBSV', 'Observasi')], default='OBSV', max_length=15),
        ),
    ]
