# Generated by Django 3.2.14 on 2022-07-10 07:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_audit_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctiveaction',
            name='evidence',
            field=models.FileField(null=True, upload_to=core.models.audit_corrective_file_path),
        ),
    ]
