# Generated by Django 3.2.14 on 2022-07-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_correctiveaction_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctiveaction',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
