# Generated by Django 3.2.14 on 2022-07-13 02:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_correctiveaction_is_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctiveaction',
            name='due_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to=core.models.audit_corrective_file_path),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='links',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
