# Generated by Django 3.2.14 on 2022-08-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20220713_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='standard',
            field=models.ManyToManyField(related_name='standards', to='core.Standard'),
        ),
    ]
